CREATE TABLE IF NOT EXISTS Game (
	game_id INTEGER PRIMARY KEY,
	name CHARACTER VARYING(64) NOT NULL,
	genre CHARACTER VARYING(32) NOT NULL,
	description CHARACTER VARYING(512) NOT NULL,
	size REAL NOT NULL CHECK (size > 0),
	esrb_rating CHARACTER VARYING(3),
	developer CHARACTER VARYING(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS Supplier (
	supplier_id INTEGER PRIMARY KEY,
	name CHARACTER VARYING(64) NOT NULL,
	address CHARACTER VARYING(128)
);

CREATE TABLE IF NOT EXISTS Supply (
	game_id INTEGER NOT NULL,
	supplier_id INTEGER NOT NULL,
	price REAL NOT NULL CHECK (price > 0),
	PRIMARY KEY (game_id, supplier_id),
	FOREIGN KEY (game_id) REFERENCES Game ON DELETE CASCADE,
	FOREIGN KEY (supplier_id) REFERENCES Supplier ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Customer (
	customer_id INTEGER PRIMARY KEY,
	first_name CHARACTER VARYING(64) NOT NULL,
	last_name CHARACTER VARYING(64) NOT NULL,
	age INTEGER CHECK (age > 12),
	password CHARACTER VARYING(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS Payment_Method (
	payment_id INTEGER PRIMARY KEY,
	customer_id INTEGER NOT NULL,
	card_number CHARACTER(16) NOT NULL,
	exp_date CHARACTER(5) NOT NULL,
	FOREIGN KEY (customer_id) REFERENCES Customer ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Review (
	review_id INTEGER GENERATED ALWAYS AS IDENTITY,
	game_id INTEGER NOT NULL,
	customer_id INTEGER NOT NULL,
	comment CHARACTER VARYING(512),
	score INTEGER NOT NULL CHECK (score >= 0 AND score <= 10),
	PRIMARY KEY (review_id, game_id, customer_id),
	FOREIGN KEY (game_id) REFERENCES Game ON DELETE CASCADE,
	FOREIGN KEY (customer_id) REFERENCES Customer ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Game_Order (
	order_id INTEGER GENERATED ALWAYS AS IDENTITY,
	date DATE NOT NULL,
	game_id INTEGER NOT NULL,
	supplier_id INTEGER NOT NULL,
	customer_id INTEGER NOT NULL,
	payment_id INTEGER NOT NULL,
	PRIMARY KEY (order_id, game_id, supplier_id, customer_id, payment_id),
	FOREIGN KEY (game_id, supplier_id) REFERENCES Supply ON DELETE CASCADE,
	FOREIGN KEY (customer_id) REFERENCES Customer ON DELETE CASCADE,
	FOREIGN KEY (payment_id) REFERENCES Payment_Method ON DELETE CASCADE
);